BEGIN;

UPDATE game SET description = 'Red Dead Redemption 2 is a sweeping open-world western that follows Arthur Morgan and the Van der Linde gang as they struggle to survive in a changing America. The game blends cinematic storytelling with an extraordinary level of environmental detail, making every town, forest, and mountain feel alive. Gunfights are weighty, horseback travel feels natural, and the world constantly reacts to the player''s choices and behavior. Its cast of characters is one of the strongest in modern gaming, with relationships that evolve naturally over the long journey. Side missions, random encounters, hunting, and camp activities give the world a rare sense of authenticity and rhythm. The emotional core of Arthur''s story gives the experience unusual depth for an open-world action game. It stands as one of the most immersive and ambitious adventures ever created.' WHERE title = 'Red Dead Redemption 2';

UPDATE game SET description = 'Grand Theft Auto V is a massive open-world crime epic set in the sun-soaked chaos of Los Santos and Blaine County. The story follows three very different protagonists whose lives collide through heists, betrayals, and explosive ambition. Switching between Michael, Franklin, and Trevor gives the campaign a dynamic structure that constantly changes the tone and pace. The city itself is packed with activities, traffic, satire, side stories, and absurd details that make it feel lively even years after release. Driving, shooting, flying, and exploration are all designed to support both cinematic missions and player freedom. The writing is sharp, cynical, and often hilarious, capturing a very specific vision of modern excess. Even after all this time, it remains one of the most influential sandbox games ever made.' WHERE title = 'Grand Theft Auto V';

UPDATE game SET description = 'Cyberpunk 2077 is a futuristic action RPG set in Night City, a neon-drenched metropolis obsessed with power, money, and body modification. Players step into the role of V, a mercenary whose rise through the city''s factions becomes entangled with dangerous technology and personal survival. The setting is one of the game''s greatest strengths, filled with dense streets, towering architecture, underground markets, and shifting social tensions. Combat allows for multiple approaches, from stealthy hacking and silent takedowns to aggressive gunplay and cybernetic abilities. The game also leans heavily into narrative choice, giving many quests a more personal and reflective tone than expected. Its strongest moments come from the atmosphere, memorable side characters, and the feeling of being lost inside an overwhelming future. Night City itself becomes a character, making the experience feel stylish, tragic, and strangely intimate.' WHERE title = 'Cyberpunk 2077';

UPDATE game SET description = 'Elden Ring is a vast dark fantasy action RPG that expands the familiar challenge of FromSoftware''s design into an enormous open world. The Lands Between are full of ruined castles, hidden caves, strange creatures, and secrets that reward curiosity at almost every turn. Combat is deliberate and demanding, asking players to study enemies, learn patterns, and refine timing with every encounter. Exploration feels unusually meaningful because the world rarely explains itself directly, leaving discovery to the player. The game''s visual design mixes beauty and decay, creating a haunting atmosphere that constantly pulls you forward. Boss battles are intense, memorable, and often spectacular in scale, while character builds offer deep freedom. It is both an uncompromising challenge and a grand adventure, which is why it resonated so strongly with so many players.' WHERE title = 'Elden Ring';

UPDATE game SET description = 'The Witcher 3: Wild Hunt is a story-driven open-world RPG centered on Geralt of Rivia, a monster hunter navigating war, politics, and personal destiny. Its world is enormous, but what truly sets it apart is how thoughtfully written its quests are, even the smallest side stories. Players travel through war-torn villages, dangerous swamps, crowded cities, and distant islands, all of which feel grounded and lived in. Combat combines swordplay, signs, alchemy, and preparation, encouraging players to treat monsters as unique threats rather than simple enemies. The game''s strongest quality is its writing, which gives nearly every character and decision emotional texture. Expansions made an already exceptional game even richer, adding some of the best content in the genre. It remains a benchmark for narrative ambition in open-world RPG design.' WHERE title = 'The Witcher 3: Wild Hunt';

UPDATE game SET description = 'God of War reimagines Kratos as a more reflective and complex character while sending him on a dangerous journey through the realms of Norse mythology. At its heart, the game is about the evolving relationship between Kratos and his son Atreus, and that emotional focus gives the story unusual strength. The Leviathan Axe feels satisfying from the first throw, and combat grows steadily deeper as the adventure continues. Environments are rich with mythic atmosphere, from frozen lakes and ancient ruins to hidden chambers and towering gods. Exploration, puzzles, and character progression are woven together with cinematic presentation that rarely breaks immersion. The camera style and seamless world transitions create a sense of constant momentum. It is both a powerful reinvention of a series and one of the most polished action adventures of its era.' WHERE title = 'God of War';

UPDATE game SET description = 'Spider-Man Remastered is a fast, cinematic superhero adventure that captures the fantasy of moving through New York City better than almost any game before it. Swinging across skyscrapers feels fluid, stylish, and endlessly satisfying, turning travel itself into one of the game''s greatest pleasures. Combat blends gadgets, counters, aerial movement, and crowd control in a way that makes every encounter look dynamic and improvisational. The story balances large-scale comic-book spectacle with a more personal portrayal of Peter Parker''s life and responsibilities. New York is filled with crimes, collectibles, side activities, and iconic landmarks that encourage constant exploration. The game also does a strong job of making its villains feel memorable and escalating the stakes naturally over time. It is an energetic and heartfelt superhero experience that understands exactly why players love Spider-Man.' WHERE title = 'Spider-Man Remastered';

UPDATE game SET description = 'Horizon Zero Dawn takes place in a striking post-apocalyptic world where nature has reclaimed the earth and mechanical beasts dominate the landscape. Players follow Aloy, a skilled hunter and outsider whose search for identity gradually uncovers the truth behind the world''s collapse. The setting is visually distinctive, mixing tribal cultures with futuristic ruins and towering machines in a way that feels fresh. Combat is built around strategy, using traps, elemental weaknesses, and careful aiming to dismantle robotic enemies piece by piece. Exploration is rewarding because the mystery of the world constantly encourages players to keep asking bigger questions. The game''s central plot becomes more compelling as its science-fiction foundations are revealed. It succeeds by combining beautiful worldbuilding, smart combat, and a strong protagonist.' WHERE title = 'Horizon Zero Dawn';

UPDATE game SET description = 'Starfield is a large-scale space RPG built around exploration, faction stories, ship travel, and the promise of discovering humanity''s future among the stars. Players create their own character and carve a path through a galaxy filled with politics, outposts, ruins, and strange worlds. The game leans into the fantasy of being a space explorer, whether that means scanning planets, upgrading ships, smuggling cargo, or joining powerful groups. Its structure gives players freedom to chase personal goals at their own pace, which is a core part of its appeal. Gunplay, ship customization, and companion interactions all support the larger sense of scale. The strongest moments often come when a quiet planet, abandoned station, or philosophical storyline captures the feeling of loneliness and wonder in space. It is an ambitious sandbox RPG that aims more for breadth and atmosphere than nonstop spectacle.' WHERE title = 'Starfield';

UPDATE game SET description = 'Resident Evil 4 is a modern reimagining of one of survival horror''s most influential games, blending tension, action, and atmosphere with remarkable confidence. Players control Leon S. Kennedy as he searches for the president''s daughter in a hostile rural region overrun by intelligent infected villagers. The remake sharpens the pacing while preserving the original''s iconic set pieces, combat encounters, and rising dread. Gunplay feels impactful, inventory management adds pressure, and enemy behavior keeps every fight unsettled and dangerous. The environments are dark, textured, and full of detail, making even familiar locations feel newly oppressive. It balances horror and action especially well, never leaning too far into either extreme. The result is a polished, intense, and highly replayable survival horror experience.' WHERE title = 'Resident Evil 4';

UPDATE game SET description = 'Portal 2 is a first-person puzzle game built around elegant mechanics, brilliant writing, and an extraordinary sense of progression. The portal gun remains one of the most creative tools in gaming, allowing players to think spatially in ways few other games attempt. Every test chamber introduces new ideas, then twists them into increasingly clever challenges that remain satisfying instead of frustrating. The dialogue from GLaDOS, Wheatley, and the supporting cast gives the experience a unique comedic voice. Cooperative mode expands the core concept even further, turning puzzle-solving into a shared performance of timing and communication. The pacing is exceptional, shifting naturally from quiet problem-solving to dramatic reveals and memorable set pieces. It is one of the smartest and most beloved puzzle adventures ever made.' WHERE title = 'Portal 2';

UPDATE game SET description = 'Cricket 24 is a broad and feature-rich cricket simulation designed for players who want licensed teams, recognizable tournaments, and a more complete modern package. The game aims to capture the rhythm of cricket through batting timing, bowling variation, field placement, and match strategy. Career progression and team management add a layer of long-term structure beyond individual matches. Stadiums, uniforms, and presentation help reinforce the feeling of official competition and global sport culture. Its appeal is strongest for players who want a dedicated cricket experience rather than an arcade shortcut. Multiplayer and custom setups also help extend replay value. For cricket fans, it offers a solid foundation with enough scale to feel like a serious sports title.' WHERE title = 'Cricket 24';

UPDATE game SET description = 'eFootball is a football simulation built around online play, licensed clubs, tactical setups, and a long-term live-service model. The game focuses on the flow of passing, positioning, and possession, aiming to recreate modern football through accessible controls and constant updates. It tries to make matches feel dynamic, with momentum swings, pressing battles, and individual player traits shaping the action. Team-building and event-based progression give players reasons to keep returning over time. Its strengths come most clearly in short competitive sessions where smart movement and timing matter. Presentation and content depth have improved gradually as the platform has evolved. At its best, it provides a modern football experience centered on strategy, familiarity, and repeat play.' WHERE title = 'eFootball™';

UPDATE game SET description = 'Black Myth: Wukong is a myth-inspired action RPG that draws heavily from Journey to the West while presenting a world filled with supernatural creatures and intense boss encounters. The game centers on fluid melee combat, magical abilities, and transformations that let encounters shift dramatically from one moment to the next. Its visual style is one of its biggest draws, with richly detailed environments and enemy designs rooted in Chinese folklore. Boss battles appear to be a major focus, emphasizing spectacle, movement, and precise reaction. The tone mixes grandeur and mystery, giving the world a sense of ancient danger and spiritual weight. Exploration and storytelling seem designed to support the larger mythic atmosphere rather than interrupt it. It stands out as an ambitious action title with strong identity and memorable presentation.' WHERE title = 'Black Myth: Wukong';

UPDATE game SET description = 'Ghost of Tsushima DIRECTORS CUT is an open-world samurai adventure set during the Mongol invasion of Tsushima Island. Players follow Jin Sakai as he struggles between traditional honor and the ruthless methods needed to protect his home. Combat is elegant and deliberate, built around stances, timing, and the visual beauty of sword duels. The island itself is one of the game''s greatest strengths, using wind, color, weather, and landscape to guide exploration in a graceful way. Stealth, combat, and traversal combine to support a story that is both personal and national in scope. The game''s tone often feels meditative, even when the action is intense. It is a polished, atmospheric adventure that delivers style, emotion, and a strong sense of place.' WHERE title = 'Ghost of Tsushima DIRECTORS CUT';

UPDATE game SET description = 'Baldurs Gate 3 is a large-scale fantasy RPG built around party choice, player freedom, and deeply reactive storytelling. Every major quest feels open to experimentation, allowing players to solve problems through combat, stealth, persuasion, magic, or complete unpredictability. The companions are memorable and layered, with personal arcs that evolve meaningfully based on choices and relationships. Turn-based combat is dense and tactical, rewarding careful use of terrain, spells, positioning, and class abilities. What makes the game special is how often it acknowledges unusual decisions instead of forcing one correct path. The world feels handcrafted and alive, packed with secrets, branching outcomes, and dramatic consequences. It is one of the most generous and flexible role-playing games released in years.' WHERE title = 'Baldurs Gate 3';

UPDATE game SET description = 'Sekiro: Shadows Die Twice is an intense action adventure built around precision swordplay, aggressive defense, and constant pressure. Rather than focusing on broad RPG customization, the game asks players to master one deeply refined combat system centered on posture, rhythm, and timing. Fights feel like duels of concentration, where hesitation is often more dangerous than direct aggression. The world draws from a dark fantasy version of Sengoku Japan, blending ruined temples, forests, castles, and supernatural horrors. Stealth and mobility allow players to approach combat creatively, but boss battles remain the true test of skill. The difficulty is high, yet the sense of mastery it creates is unusually satisfying. It is one of the sharpest and most disciplined combat systems FromSoftware has ever built.' WHERE title = 'Sekiro™: Shadows Die Twice - GOTY Edition';

UPDATE game SET description = 'Resident Evil Village is a first-person survival horror adventure that blends gothic horror, action, and strange fairy-tale imagery into a memorable nightmare. Players return as Ethan Winters and are drawn into a remote village ruled by disturbing figures and hidden threats. The game shifts between fear, exploration, resource tension, and explosive confrontations with strong pacing. Each major area has a distinct identity, helping the journey feel varied instead of repetitive. Gunplay is accessible but still tense, especially when ammunition and healing supplies are limited. Its villains are theatrical and memorable, giving the story a larger-than-life edge without losing its horror core. Village succeeds by being creepy, stylish, and willing to embrace both terror and spectacle.' WHERE title = 'Resident Evil Village';

UPDATE game SET description = 'Forza Horizon 5 is an open-world driving festival set across a vibrant version of Mexico filled with deserts, jungles, volcanoes, highways, and towns. The game is built around speed and freedom, letting players drift between races, stunts, exploration, and collection with almost no friction. Its car handling manages to feel approachable and exciting while still giving distinct identity to different vehicle types. Events are varied and often spectacular, keeping momentum high even over long play sessions. The world is beautiful and inviting, making simple driving feel rewarding even when no objective is active. Multiplayer systems and seasonal updates help keep the world lively over time. It is one of the most polished and welcoming arcade racing games available.' WHERE title = 'Forza Horizon 5';

UPDATE game SET description = 'Lies of P is a dark action RPG that reimagines the Pinocchio story through a grim, mechanical city consumed by violence and decay. Its combat is deliberate and challenging, drawing on stamina management, perfect guards, weapon variety, and careful timing. The Belle Époque-inspired setting gives the game a distinctive visual identity that feels elegant and eerie at the same time. Exploration steadily reveals hidden paths, strange residents, and unsettling lore that deepen the tone of the world. Weapon assembly and character customization add meaningful room for experimentation. Boss encounters are demanding and dramatic, often pushing players to refine technique instead of relying on brute force. It is a confident and stylish soulslike with its own atmosphere and personality.' WHERE title = 'Lies of P';

UPDATE game SET description = 'Hades II expands on the fast, stylish roguelike formula of its predecessor while introducing a new protagonist and a fresh mythological direction. The game is built around rapid combat, layered upgrades, and repeated runs that gradually deepen both player skill and story understanding. Like the first game, it aims to make every failure feel like progress rather than punishment. The art direction, music, and character writing give the underworld and beyond a distinctive energy that stays engaging across many attempts. Combat appears faster and more varied, with tools and abilities that encourage experimentation. Relationships with gods and other characters remain central to the tone, giving warmth to a game about relentless struggle. It feels like a bold continuation of one of the strongest action roguelikes in modern gaming.' WHERE title = 'Hades II';

UPDATE game SET description = 'HELLDIVERS 2 is a cooperative shooter built around chaos, teamwork, and the constant risk of friendly fire in large-scale missions. Players drop onto hostile planets to complete objectives while fighting overwhelming alien threats with limited time and escalating pressure. Its combat is immediate and satisfying, but the real identity of the game comes from coordination and disaster recovery. Stratagems let players call in weapons, turrets, support gear, and devastating attacks, though using them carelessly can be just as dangerous to allies. The satirical military tone adds personality without undercutting the tension of the action. Every mission can swing from controlled efficiency to total panic in seconds. It is a multiplayer game that thrives on cooperation, improvisation, and stories born from failure as much as success.' WHERE title = 'HELLDIVERS™ 2';

UPDATE game SET description = 'Dragons Dogma 2 is a large fantasy action RPG built around exploration, emergent combat, and a world that often feels indifferent to the player''s comfort. Travel is dangerous, night is threatening, and even routine journeys can turn into memorable encounters with monsters or unexpected events. The pawn system remains one of the game''s defining ideas, giving players AI companions that feel useful, expressive, and strategically important. Combat is dynamic and physical, with climbing, spellcasting, knockdowns, and class abilities all shaping battles in dramatic ways. The world encourages curiosity rather than speed, rewarding players who wander off the main road. Its structure can feel old-fashioned in places, but that roughness also gives it personality. At its best, it feels like a true high-fantasy adventure where discovery matters as much as victory.' WHERE title = 'Dragons Dogma 2';

UPDATE game SET description = 'Hollow Knight is a beautifully crafted action adventure set in the haunting underground kingdom of Hallownest. The world is interconnected and mysterious, encouraging slow exploration, careful observation, and repeated returns to earlier areas with new abilities. Combat is clean and responsive, making even small encounters feel meaningful while boss fights demand patience and precision. The visual style is simple but striking, using animation, architecture, and music to create a melancholy sense of history and loss. Storytelling is subtle, allowing lore to emerge through ruins, dialogue fragments, and environmental detail. Progression feels rewarding because movement itself steadily becomes more expressive and skillful. It is one of the finest modern metroidvanias, defined by atmosphere, challenge, and elegant design.' WHERE title = 'Hollow Knight';

UPDATE game SET description = 'Disco Elysium - The Final Cut is a role-playing game unlike almost any other, focusing on psychology, conversation, and self-destruction rather than conventional combat. Players control a deeply broken detective trying to solve a murder while also reconstructing his own identity. The game''s skill system turns internal thoughts and personality traits into active voices that shape perception, decisions, and failures. Its world is politically layered, emotionally messy, and written with unusual literary ambition. Dialogue is the core mechanic, but it feels every bit as tense and dramatic as action in more traditional games. The investigation constantly branches into philosophy, memory, comedy, and tragedy. It is a bold, unforgettable RPG that proves words and character can carry a game with extraordinary power.' WHERE title = 'Disco Elysium - The Final Cut';

UPDATE game SET description = 'DEATH STRANDING DIRECTORS CUT is a strange and thoughtful action adventure built around delivery, isolation, terrain, and connection. Players guide Sam Porter Bridges across a shattered America, carrying supplies through landscapes that can be as threatening as any enemy. Movement is central to the experience, turning weight, balance, weather, and route planning into meaningful gameplay systems. The world feels lonely and surreal, full of haunting science-fiction imagery and unusual narrative ideas. Combat exists, but the emotional identity of the game comes more from endurance, rebuilding, and the quiet satisfaction of helping others. Online systems subtly connect players through structures and tools, reinforcing the game''s themes without direct co-op. It is unusual, meditative, and often deeply memorable precisely because it refuses to behave like a typical blockbuster.' WHERE title = 'DEATH STRANDING DIRECTORS CUT';

UPDATE game SET description = 'Persona 5 Royal is a stylish turn-based RPG that combines school life, dungeon exploration, and supernatural rebellion into a highly distinctive experience. Players balance daily routines, friendships, and personal growth while also entering cognitive palaces to confront corruption in dramatic fashion. Combat is smooth and strategic, rewarding elemental knowledge, team coordination, and careful preparation. The soundtrack, interface, and visual direction give the game a level of identity few RPGs can match. Its social systems make time management meaningful, encouraging players to think about relationships as much as battle strength. The story is long but consistently energized by strong character dynamics and a clear sense of purpose. It is one of the most confident and stylish JRPGs of its generation.' WHERE title = 'Persona 5 Royal';

UPDATE game SET description = 'Monster Hunter: World is an action RPG built around tracking, hunting, and mastering enormous creatures in a living ecosystem. Each monster feels like a real presence with patterns, territories, and behaviors that players gradually learn over time. Combat is deliberate and highly weapon-specific, making the choice of loadout almost as important as player skill. Hunting is not just about fighting, but also about preparation, crafting, positioning, and understanding the environment. The world design emphasizes scale and ecological detail, helping every hunt feel like part of a larger natural system. Cooperative play adds even more excitement, turning difficult encounters into shared tactical battles. It is one of the most rewarding games for players who enjoy progression through knowledge and mastery.' WHERE title = 'Monster Hunter: World';

UPDATE game SET description = 'NieR:Automata is an action RPG that combines stylish combat, philosophical themes, and shifting narrative structure in a deeply unusual way. Set in a distant war between androids and machines, the game explores identity, purpose, consciousness, and grief through repeated perspectives and evolving context. Combat is fast and elegant, blending melee attacks, ranged support, dodges, and aerial movement into a smooth flow. The soundtrack is extraordinary, often carrying the emotional weight of scenes with haunting vocal tracks and layered melodies. What begins as a stylish science-fiction story gradually becomes something far stranger and more reflective. Multiple routes are not just replay content, but part of the intended narrative design. It is emotional, ambitious, and one of the most distinctive RPGs of the last decade.' WHERE title = 'NieR:Automata™';

UPDATE game SET description = 'Armored Core VI Fires of Rubicon revives mech combat with speed, aggression, and intense customization at the center of the experience. Players build machines from interchangeable parts, tuning mobility, armor, weapons, and energy use to suit different missions and strategies. Battles are fast and demanding, rewarding adaptation, positioning, and pressure rather than passive defense. The industrial science-fiction setting gives the game a hard, mechanical tone that suits its combat perfectly. Missions are compact and focused, but the encounter design makes them feel dense and memorable. Boss fights in particular ask players to rethink builds and tactics instead of relying on one comfortable style. It is a powerful return for the series and a standout action game in its own right.' WHERE title = 'Armored Core VI Fires of Rubicon';

UPDATE game SET description = 'It Takes Two is a co-op adventure built entirely around collaboration, constantly introducing new mechanics that require two players to communicate and work together. The story follows a struggling couple transformed into dolls, and while the premise is whimsical, the emotional core is sincere. Every chapter changes the gameplay in surprising ways, moving from platforming and puzzles to action, rhythm, minigames, and unexpected genre shifts. The variety keeps the adventure fresh and gives both players equal importance. Its level design is imaginative, playful, and often visually charming. Cooperative problem-solving feels natural because the game is built from the ground up for shared play. It is one of the most inventive and enjoyable co-op experiences available.' WHERE title = 'It Takes Two';

UPDATE game SET description = 'Sid Meiers Civilization VI is a grand strategy game about guiding a civilization from ancient beginnings into the modern future. Players expand cities, manage resources, research technologies, shape governments, and compete with rivals through war, culture, religion, and diplomacy. The turn-based format makes every decision feel deliberate, especially as the map becomes more complex over time. City planning is especially important, since district placement and terrain can strongly influence long-term success. Each civilization has distinct abilities, encouraging different styles of play and experimentation. Sessions can become deeply absorbing because one more turn often leads to ten more. It remains one of the most accessible yet rewarding strategy sandboxes in the genre.' WHERE title = 'Sid Meiers Civilization VI';

UPDATE game SET description = 'Dead Space is a survival horror experience set aboard a massive mining ship consumed by grotesque alien corruption. Players control Isaac Clarke, an engineer forced into combat and survival against horrific necromorphs stalking dark corridors and shattered systems. The game''s atmosphere is one of its greatest strengths, using sound design, lighting, and environmental detail to create constant unease. Combat feels distinct because enemies are most effectively stopped through strategic dismemberment rather than simple headshots. The setting is claustrophobic and oppressive, turning every hallway into a source of suspicion. Narrative and presentation work together to maintain tension without overexplaining the terror. It is a sharp and terrifying science-fiction horror game with lasting impact.' WHERE title = 'Dead Space';

UPDATE game SET description = 'Half-Life: Alyx is a landmark VR shooter that demonstrates how immersive, tactile, and atmospheric virtual reality gaming can be. Set in the Half-Life universe, it places players directly inside ruined streets, dark interiors, and alien-infested spaces with extraordinary presence. Gun handling, reloading, object interaction, and environmental puzzle-solving all feel carefully designed for VR rather than adapted to it. The pacing moves confidently between suspense, combat, exploration, and quiet discovery. Worldbuilding is exceptional, making every room feel intentionally crafted and full of narrative detail. The sense of scale and physical engagement transforms familiar shooter ideas into something far more personal. It is widely regarded as one of the most important and polished VR games ever released.' WHERE title = 'Half-Life: Alyx';

UPDATE game SET description = 'Resident Evil 2 is a survival horror remake that modernizes a classic while preserving its fear, tension, and identity. Set in the collapsing Raccoon City police station and surrounding nightmare, the game follows Leon and Claire through overlapping but distinct routes. Resource scarcity, locked doors, and relentless pursuers make every decision feel meaningful. The over-the-shoulder perspective creates immediacy without sacrificing the dread and deliberate pacing of the original. Enemy design, sound cues, and lighting work together to keep the pressure constant. Exploration is tightly structured, with satisfying backtracking as new tools open old paths. It is one of the strongest examples of how to remake a beloved horror game with care and confidence.' WHERE title = 'Resident Evil 2';

UPDATE game SET description = 'Devil May Cry 5 is a stylish action game built around fast combat, technical expression, and pure momentum. Players swap between multiple protagonists, each with distinct mechanics that keep the campaign varied and mechanically rich. The game encourages creativity rather than mere survival, rewarding players for fighting with flair and improvisation. Weapons are dramatic, movement is sharp, and enemy encounters are designed to support juggling, counters, and crowd control. Its presentation is flashy without becoming exhausting, balancing spectacle with strong combat readability. The story serves mostly as a vehicle for character energy, tone, and escalating chaos. It is a celebration of action design at its most confident and entertaining.' WHERE title = 'Devil May Cry 5';

UPDATE game SET description = 'DOOM Eternal is a ferocious first-person shooter built around motion, aggression, and total commitment to attack. The game pushes players to manage health, armor, ammunition, and positioning all at once, turning every arena into a high-speed combat puzzle. Enemies are dangerous individually, but the true challenge comes from handling entire battle spaces under intense pressure. Weapons feel powerful and distinct, and the game constantly asks players to rotate through them intelligently. Its pace is relentless, but the rhythm becomes deeply satisfying once the systems click. Platforming and traversal add verticality and keep movement central to the experience. It is one of the most mechanically focused and exhilarating shooters of recent years.' WHERE title = 'DOOM Eternal';

UPDATE game SET description = 'Hades is a fast-paced roguelike action game that combines excellent combat with one of the most rewarding repetition loops in the genre. Players control Zagreus as he repeatedly attempts to escape the Underworld, growing stronger and learning more with each failure. The game makes repetition meaningful by tying story progression, character relationships, and mechanical upgrades directly to repeated runs. Combat is responsive and fluid, with weapon styles and boons that encourage experimentation rather than routine. The writing is witty and surprisingly warm, giving mythological characters distinct personalities and strong chemistry. Art, music, and pacing come together to make every attempt feel energizing. It is a near-perfect example of how roguelikes can blend action, progression, and narrative.' WHERE title = 'Hades';

UPDATE game SET description = 'Control Ultimate Edition is a supernatural action thriller set inside the Federal Bureau of Control, a government building filled with shifting architecture and impossible objects. Players control Jesse Faden as she searches for answers about her past while navigating escalating paranormal threats. Combat mixes firearms with telekinetic powers, making encounters feel dynamic and visually striking. The setting is one of the game''s greatest achievements, turning office spaces into surreal arenas of mystery and tension. Lore is scattered through reports, recordings, and environments, encouraging players to piece together the larger picture themselves. The tone balances creepy uncertainty with bursts of confidence and power. It is a stylish and imaginative action game with a uniquely unsettling world.' WHERE title = 'Control Ultimate Edition';

UPDATE game SET description = 'The Last of Us Part I is a story-driven action adventure set in a brutal post-apocalyptic world where survival often comes at a moral cost. Players follow Joel and Ellie on a journey across ruined America, and the emotional power of their relationship defines the entire experience. Combat is tense and grounded, emphasizing scarcity, improvisation, and the danger of every encounter. Exploration of abandoned cities and reclaimed spaces reinforces the sense of a world that has moved on without humanity. The writing is natural, restrained, and devastating when it needs to be. Small conversations, visual details, and quiet moments are just as important as the big narrative turns. It remains one of the most admired examples of storytelling in games.' WHERE title = 'The Last of Us Part I';

UPDATE game SET description = 'UNCHARTED: Legacy of Thieves Collection brings together cinematic treasure-hunting adventures defined by fast pacing, charismatic characters, and globe-spanning spectacle. The collection showcases environments that move from ancient ruins and urban rooftops to lush wilderness and collapsing monuments. Climbing, shooting, puzzle-solving, and banter are woven together into a breezy rhythm that keeps the story moving forward. Nathan Drake and the supporting cast help give the series its distinctive warmth and charm. The presentation leans heavily into blockbuster energy, but the games also make room for quieter emotional beats. Set pieces are often elaborate and memorable without losing control or clarity. It is a polished adventure package built to entertain from beginning to end.' WHERE title = 'UNCHARTED: Legacy of Thieves Collection';

UPDATE game SET description = 'Marvels Guardians of the Galaxy is a story-driven action adventure focused on team chemistry, humor, and surprisingly sincere character work. Players control Star-Lord, but much of the game''s appeal comes from managing and interacting with the wider Guardians team during both combat and dialogue. Battles are energetic and colorful, built around issuing commands and syncing abilities rather than controlling each character directly. The game''s writing gives the team room to feel dysfunctional, funny, vulnerable, and believable all at once. Music, visual style, and cosmic worldbuilding support its upbeat but emotional tone. Its strongest moments come from the way it balances absurdity with genuine heart. It is a superhero adventure that succeeds because it cares about its characters as much as its action.' WHERE title = 'Marvels Guardians of the Galaxy';

UPDATE game SET description = 'FINAL FANTASY VII REMAKE INTERGRADE reimagines one of the most iconic RPG stories in gaming with modern presentation, expanded characterization, and real-time combat depth. The world of Midgar feels more detailed and alive, turning what was once a brief opening act into a full dramatic journey. Combat blends action and command-based strategy, allowing players to swap characters, build pressure, and manage abilities in satisfying ways. The cast receives far more screen time and emotional nuance, making familiar moments feel fresh instead of purely nostalgic. Music, cinematics, and art direction carry enormous emotional weight throughout the story. The remake also embraces mystery by playing with expectations rather than simply repeating the original beat for beat. It is both a celebration of a classic and a bold reinterpretation of it.' WHERE title = 'FINAL FANTASY VII REMAKE INTERGRADE';

UPDATE game SET description = 'TEKKEN 8 is a modern fighting game built around sharp movement, strong visual impact, and a deep competitive system. Its characters remain distinct and expressive, with fighting styles that reward dedication and matchup knowledge. The new mechanics increase pressure and tempo, helping matches feel more explosive without removing the tactical core of the series. Animations are crisp and heavy, making every hit feel meaningful and readable. Single-player content and presentation help support newcomers, while experienced players can still dive into technical mastery. The roster carries decades of legacy, rivalries, and recognizable style. It is a confident step forward for one of the most important fighting game franchises.' WHERE title = 'TEKKEN 8';

UPDATE game SET description = 'Street Fighter 6 is a vibrant and highly polished fighting game that balances accessibility for new players with serious depth for veterans. The core combat is built around spacing, mind games, reactions, and resource management, but new systems help make those layers easier to understand. The visual style is bold and energetic, giving each fighter and arena clear personality. Controls, training tools, and onboarding features do a notably good job of welcoming players who might normally avoid the genre. At the same time, high-level play remains rich and expressive, which is crucial for a long-term competitive game. Online infrastructure and overall package quality give the game strong staying power. It feels like both a celebration and a reinvention of Street Fighter''s core strengths.' WHERE title = 'Street Fighter 6';

UPDATE game SET description = 'Ori and the Will of the Wisps is a visually stunning platform adventure that builds on the strengths of its predecessor while expanding combat, exploration, and emotional storytelling. Movement is fluid and elegant, making traversal itself feel joyful even in difficult sections. The world is full of color, atmosphere, and layered spaces that reward attention and mastery. Combat is more developed than before, but the heart of the experience still lies in precision movement and emotional tone. The soundtrack and visual direction carry enormous weight, often making simple moments feel grand and intimate at the same time. Storytelling is sincere and melodic rather than overly complicated, which suits the game perfectly. It is one of the most graceful and emotionally resonant platformers of its generation.' WHERE title = 'Ori and the Will of the Wisps';

UPDATE game SET description = 'A Plague Tale: Requiem is a dark narrative adventure that follows siblings Amicia and Hugo through a brutal world shaped by disease, war, and fear. The game emphasizes vulnerability, forcing players to think carefully about stealth, resource use, and when confrontation is worth the risk. Its environments are rich with historical mood, from ruined villages and crowded ports to grim battlefields and decaying estates. The emotional core is the relationship between its two leads, whose bond carries the story through moments of tenderness and devastation. Swarms of rats remain one of the game''s most striking visual and mechanical features, creating scenes of genuine dread. The sequel expands the scale of the world without losing the intimacy of the characters'' struggle. It is a powerful and tragic story-rich adventure.' WHERE title = 'A Plague Tale: Requiem';

UPDATE game SET description = 'Metro Exodus is a post-apocalyptic shooter that combines survival tension, atmospheric exploration, and narrative-driven travel across a shattered Russia. Rather than staying confined to one type of environment, the game moves through varied regions that each bring their own tone, threats, and visual identity. Gunplay is grounded and dangerous, especially when ammunition is scarce and equipment must be maintained. The game''s world is harsh, but it also makes room for quiet moments that build a sense of companionship and endurance. Weather, light, sound, and sparse resources all contribute to the feeling of being on a fragile journey. The pacing alternates effectively between open-ended exploration and tightly scripted tension. It is a strong blend of shooter mechanics and immersive survival storytelling.' WHERE title = 'Metro Exodus';

UPDATE game SET description = 'Celeste is a demanding platformer built around precision movement, instant restarts, and a surprisingly heartfelt story about anxiety, self-doubt, and perseverance. The controls are exceptionally tight, which is essential because the game asks for repeated attempts and exact timing. Difficulty rises steadily, but the design remains fair enough that failure becomes part of the rhythm rather than a punishment. The pixel art and soundtrack work together beautifully, creating a strong emotional tone without overwhelming the gameplay. Beyond its challenge, the game resonates because it links the act of climbing to inner struggle in a direct and honest way. Optional content gives experts even more to master without blocking the core story. It is one of the clearest examples of difficulty used in service of meaning.' WHERE title = 'Celeste';

UPDATE game SET description = 'No Mans Sky is a space exploration game built around travel, discovery, crafting, and the fantasy of wandering through a practically endless universe. Players land on strange planets, gather resources, build bases, upgrade ships, and gradually shape their own personal journey through the stars. What makes the game compelling is the sense of scale and the constant possibility of seeing something unfamiliar just beyond the next jump. Over time, updates have made the experience much broader, adding more systems and activities without losing its exploratory core. The atmosphere often shifts between loneliness and wonder, especially on quiet planets with unusual weather or wildlife. Cooperative options and construction tools also let players turn isolation into shared creativity. It is a redemption story as much as a game, now known for freedom, scale, and ongoing reinvention.' WHERE title = 'No Mans Sky';

COMMIT;


BEGIN;

UPDATE game SET description = 'Sea of Thieves is a shared-world pirate adventure built around sailing, teamwork, treasure hunting, and the unpredictable chaos of the open sea. The game shines most when played with friends, because managing a ship, scanning the horizon, and surviving sudden disasters all feel better as a group effort. Its ocean is beautiful and dynamic, with storms, waves, and changing light giving every voyage a strong sense of atmosphere. Encounters with other crews create some of the game''s best stories, whether through combat, alliances, betrayal, or simple panic. Quests provide structure, but much of the magic comes from unexpected moments that emerge naturally during travel. The stylized presentation keeps the world playful even when the danger rises. It is a multiplayer sandbox that succeeds because it constantly turns simple goals into memorable adventures.' WHERE title = 'Sea of Thieves';

UPDATE game SET description = 'Mass Effect Legendary Edition brings together one of gaming''s most beloved science-fiction trilogies in a polished and accessible package. Across all three games, players guide Commander Shepard through a galaxy threatened by extinction, shaping relationships, alliances, and major outcomes along the way. What makes the series special is how choices and bonds carry emotional weight across an enormous arc. Combat and exploration evolve from one entry to the next, but the heart of the trilogy remains its characters and worldbuilding. Alien cultures, political tensions, and squadmate loyalty missions give the universe real texture and identity. The remaster helps modernize the experience while preserving the strengths that made the series iconic. It remains one of the most important examples of large-scale narrative RPG storytelling.' WHERE title = 'Mass Effect Legendary Edition';

UPDATE game SET description = 'Days Gone is an open-world survival adventure set in a post-pandemic America overrun by infected creatures and fractured human factions. Players control Deacon St. John, a drifter whose journey mixes personal grief, motorcycle travel, and desperate survival. The bike is central to the experience, acting not only as transportation but as a tool that must be repaired, upgraded, and protected. The Pacific Northwest setting gives the world a rugged identity, with forests, roads, camps, and abandoned towns creating a convincing sense of distance. Large hordes of infected are one of the game''s standout features, turning encounters into frantic battles of planning, traps, and endurance. While the story takes time to unfold, it grows stronger as its characters and relationships deepen. The result is a rough but emotionally sincere open-world journey with strong atmosphere.' WHERE title = 'Days Gone';

UPDATE game SET description = 'Detroit: Become Human is a branching narrative adventure that explores android consciousness, morality, and social unrest in a near-future city. Players follow multiple protagonists whose stories intersect through choice-driven scenes that can lead to very different outcomes. The game''s structure makes every decision feel immediate, whether it involves compassion, rebellion, sacrifice, or fear. Its presentation is highly cinematic, using performance capture and visual detail to emphasize emotion and tension. What gives the experience its power is the way it invites players to question control, freedom, and identity from multiple viewpoints. Replaying scenes can reveal just how many paths were possible all along. It is a polished interactive drama built around consequence, empathy, and speculation about what it means to be alive.' WHERE title = 'Detroit: Become Human';

UPDATE game SET description = 'Batman: Arkham Knight is a superhero action game that combines stealth, free-flow combat, and open-world exploration in a dark version of Gotham City. Players once again become Batman, gliding across rooftops, hunting criminals, and facing a city pushed toward collapse by fear and chaos. Combat remains fluid and satisfying, allowing players to chain strikes, counters, gadgets, and takedowns with confidence. Predator encounters continue to be a defining strength, turning enclosed spaces into tactical stealth playgrounds. Gotham itself is detailed and atmospheric, full of rain, neon, and decay that suits the character perfectly. The Batmobile adds scale and spectacle, even if it changes the rhythm of the series in noticeable ways. It is a stylish, feature-rich conclusion to the Arkham trilogy.' WHERE title = 'Batman: Arkham Knight';

UPDATE game SET description = 'Remnant II is a cooperative action shooter that blends firearm combat, melee options, class systems, and difficult boss fights into a flexible RPG structure. Players travel through shifting worlds full of strange enemies, secrets, and alternate layouts that make repeated playthroughs feel rewarding. Combat is challenging without becoming rigid, encouraging adaptation through archetypes, weapon mods, and teamwork. The procedural elements help each campaign feel slightly different, giving exploration a stronger sense of uncertainty. Boss encounters often demand observation and quick reactions, especially when playing solo. Co-op significantly enhances the experience, turning intense battles into shared problem-solving. It is a strong follow-up that builds on the original''s unusual mix of shooter action and fantasy danger.' WHERE title = 'Remnant II';

UPDATE game SET description = 'Star Wars Jedi: Survivor continues Cal Kestis''s story with a larger world, stronger traversal, and a more confident sense of cinematic adventure. The game expands on the combat foundations of Fallen Order by adding more stances, more movement options, and more expressive encounter design. Lightsaber battles feel energetic and responsive, especially as players learn how different forms suit different threats. Exploration is broader this time, with hub-like areas, hidden routes, and optional activities that give the world more room to breathe. The tone balances personal struggle, resistance, and the weight of survival in an era dominated by the Empire. Its best moments come when spectacle and emotional character beats work together naturally. It is a bigger and more polished continuation of Cal''s journey.' WHERE title = 'Star Wars Jedi: Survivor™';

UPDATE game SET description = 'STAR WARS Jedi: Fallen Order is a story-driven action adventure that follows Cal Kestis as he tries to survive the aftermath of Order 66 and reconnect with the Force. The game combines lightsaber combat, platforming, environmental puzzles, and metroidvania-style exploration into a cohesive structure. Combat rewards timing, parries, and patience rather than pure aggression, giving duels a satisfying rhythm. The planets are designed with enough verticality and locked-off areas to encourage return visits as new abilities are unlocked. Its strongest appeal comes from delivering a focused single-player Star Wars experience during a time when many players were hungry for exactly that. The story gives Cal and his companions enough room to become emotionally grounded rather than just functional. It is a solid and memorable Jedi adventure with strong atmosphere and momentum.' WHERE title = 'STAR WARS Jedi: Fallen Order™';

UPDATE game SET description = 'Dying Light 2 Stay Human is an open-world survival action game built around first-person parkour, urban traversal, and dangerous encounters with the infected. Movement is central to the experience, and the ability to leap across rooftops, climb buildings, and escape danger quickly gives the game a unique sense of speed. Day and night create very different moods, with nighttime bringing greater rewards but far more terrifying risks. Combat mixes improvised weapons, environmental hazards, and close-range desperation in a way that suits the ruined city setting. Player decisions also shape factions and districts, giving parts of the world a reactive feel. The strongest moments often come from rooftop travel and panic-filled escapes rather than direct fighting. It is an energetic survival adventure defined by motion and pressure.' WHERE title = 'Dying Light 2 Stay Human: Reloaded Edition';

UPDATE game SET description = 'The Elder Scrolls V: Skyrim Special Edition is a legendary open-world fantasy RPG that continues to attract players because of its scale, freedom, and atmosphere. As the Dragonborn, players can wander through mountains, crypts, cities, and wilds while shaping a personal path through quests, guilds, and character builds. The game''s greatest strength is how naturally it supports both grand adventures and quiet roleplay. Magic, stealth, melee, crafting, and exploration all combine to make progression feel personal rather than prescribed. Its northern setting is filled with mythic tension, from dragon attacks and civil war to ancient ruins and forgotten prophecies. Even after many years, the world remains easy to get lost in for hours at a time. It is one of the most enduring fantasy sandboxes ever created.' WHERE title = 'The Elder Scrolls V: Skyrim Special Edition';

UPDATE game SET description = 'Fallout 4 is an open-world RPG set in a devastated future where ruins, radiation, and strange communities define everyday survival. Players emerge from vault life into the Commonwealth, searching for answers while also deciding what kind of person they want to become in a fractured society. Gunplay is more immediate than in earlier entries, giving exploration and combat a smoother rhythm. Base building adds a management layer that encourages players to invest in the world physically rather than just move through it. The retro-futuristic tone remains one of the game''s strongest qualities, mixing dark humor with bleak collapse. Factions, companions, and environmental storytelling help make the wasteland feel full of histories and tensions. It is a broad and highly moddable sandbox RPG with a distinct identity.' WHERE title = 'Fallout 4';

UPDATE game SET description = 'Red Dead Redemption is a western action adventure centered on John Marston, a former outlaw forced back into violence by the government. The game''s world captures the dying frontier with dusty towns, dangerous roads, and a sense of historical transition that gives the journey unusual melancholy. Its story is tightly focused, using revenge, duty, and personal cost to drive the player forward. Gunfights, horseback travel, and side activities support the fantasy of living in a fading western landscape. The writing balances humor, tragedy, and social commentary in a way that still holds up strongly. John Marston remains one of Rockstar''s most compelling protagonists because of the quiet sadness beneath his toughness. It is a defining western game and an important foundation for the series'' later evolution.' WHERE title = 'Red Dead Redemption';

UPDATE game SET description = 'Assassins Creed Mirage is a more focused entry in the long-running series, emphasizing stealth, urban traversal, and targeted assassinations over sprawling RPG progression. Set in Baghdad, the game leans into dense streets, rooftops, and social stealth in ways that recall earlier Assassin''s Creed titles. Basim''s story gives the narrative a more personal and introspective tone than some of the larger recent entries. Assassination tools, movement routes, and compact mission design encourage careful planning instead of brute-force combat. The city itself is full of detail and atmosphere, helping the return to a more classical structure feel intentional rather than small. It is less about overwhelming scale and more about precision and identity. For many players, that focus is exactly what makes it refreshing.' WHERE title = 'Assassins Creed Mirage';

UPDATE game SET description = 'Assassins Creed Valhalla is a huge action RPG that follows Eivor through conquest, alliance-building, and settlement life in Dark Ages England. The game combines raiding, exploration, mythic storylines, and political maneuvering inside an enormous open world. Combat is heavier and more direct than in earlier entries, fitting the Viking theme through axes, shields, and brutal impact. The settlement system gives the player a home base that slowly evolves with progress, reinforcing long-term attachment to the journey. Regional arcs make the structure feel episodic, with each territory acting like a chapter in a wider saga. Mythological elements add a larger spiritual dimension to the story without replacing its historical core. It is a vast, content-rich adventure for players who enjoy immersion through scale and accumulation.' WHERE title = 'Assassins Creed Valhalla';

UPDATE game SET description = 'Far Cry 6 is an open-world shooter set in Yara, a tropical dictatorship struggling under oppression and rebellion. Players fight as Dani Rojas, joining a guerrilla movement to challenge a brutal regime across cities, coasts, forests, and military strongholds. The game leans into improvisation, allowing players to combine weapons, gadgets, animal companions, and explosive tools in creative ways. Open-world design emphasizes player freedom, with outposts, side missions, treasure hunts, and combat spaces supporting many different approaches. Its presentation is colorful and chaotic, mixing serious political framing with playful weapon concepts and large-scale destruction. The setting helps the game stand out visually, especially when travel and conflict reveal Yara''s beauty and violence side by side. It is a confident, energetic sandbox shooter that knows exactly what kind of fun it wants to deliver.' WHERE title = 'Far Cry 6';

UPDATE game SET description = 'Borderlands 3 is a looter shooter built around over-the-top weapons, fast co-op action, and constant reward loops. The gun variety is one of its biggest strengths, making loot drops feel exciting because weapons often behave in absurd and distinctive ways. Character classes offer enough identity to support multiple playstyles, whether players prefer mobility, pets, raw damage, or support abilities. The campaign bounces between planets and factions, keeping the visual palette broad even when the humor stays consistently loud. Co-op play enhances nearly everything, turning chaotic battles into shared spectacles of explosions and improvisation. Its endgame systems and post-launch support also help extend replay value for dedicated players. It is a colorful and highly kinetic shooter that thrives on excess.' WHERE title = 'Borderlands 3';

UPDATE game SET description = 'Titanfall 2 is a science-fiction shooter celebrated for its remarkable movement, excellent campaign design, and unforgettable mech combat. Players shift between agile on-foot parkour and the heavy power of Titans, creating a rhythm unlike almost any other FPS. The campaign is especially loved because it introduces new ideas constantly, making every level feel purposeful and surprising. Gunplay is smooth and expressive, but the movement system is what gives the game its signature energy. The bond between pilot and Titan also gives the story more emotional resonance than many expected from the genre. Multiplayer extends the same speed and creativity into competitive matches that reward momentum and precision. It remains one of the most admired shooters of its era.' WHERE title = 'Titanfall® 2';

UPDATE game SET description = 'Battlefield 1 is a large-scale military shooter that uses the First World War as the foundation for dramatic, atmospheric, and often chaotic multiplayer battles. The game is especially effective at presentation, using sound, weather, destruction, and visual detail to create a sense of scale and intensity. Classes, vehicles, and shifting frontline objectives help matches feel dynamic rather than static. Its campaign vignettes also give brief but memorable perspectives on different fronts of the war. Weapons and movement are tuned to create tension without sacrificing playability or spectacle. More than many shooters, it succeeds at making conflict feel overwhelming and cinematic. It stands out as one of the strongest modern Battlefield entries.' WHERE title = 'Battlefield™ 1';

UPDATE game SET description = 'Battlefield V is a team-based military shooter that returns to World War II with squad mechanics, environmental destruction, and strong moment-to-moment combat. The game focuses on positioning, support roles, and coordinated movement in ways that reward teamwork. Gunplay is crisp and satisfying, especially in medium-range encounters where player awareness matters as much as reflex. Vehicles and combined-arms battles remain central to the identity of the series, adding scale and unpredictability to many matches. While it had a complicated post-launch reputation, the core combat systems are often praised for their immediacy and polish. Maps and modes allow for both more tactical pacing and full chaotic warfare. It is a capable large-scale shooter with strong mechanical foundations.' WHERE title = 'Battlefield™ V';

UPDATE game SET description = 'Valheim is a survival sandbox inspired by Norse mythology, built around exploration, building, resource gathering, and steady progression through dangerous biomes. The game''s world feels open and inviting, but also quietly threatening, especially when storms roll in or the wilderness turns hostile at night. Building systems are flexible enough to support both practical outposts and elaborate halls, which is a huge part of the game''s appeal. Combat is straightforward but meaningful, especially as tougher enemies force better preparation. Co-op play turns the experience into a satisfying cycle of expedition, crafting, and shared achievement. The visual style is simple, yet the lighting and environmental mood often make it unexpectedly beautiful. It is one of the most absorbing survival games for players who enjoy long-form progression and communal play.' WHERE title = 'Valheim';

UPDATE game SET description = 'Palworld is an open-world survival game that mixes creature collecting, crafting, shooting, and base management in a way that feels deliberately strange and highly watchable. Players capture companion creatures and then use them for combat, work, exploration, and production in a world full of systems to optimize. That contrast between cute design and hard survival utility is a big part of the game''s unusual identity. Exploration is broad and often rewarding, with different environments, enemy camps, and material demands pushing players outward. Base growth becomes increasingly important as the game progresses, especially when automation begins to take shape. Cooperative play adds more chaos and creativity to the entire loop. It succeeds because it embraces weirdness while still being a functional survival sandbox.' WHERE title = 'Palworld';

UPDATE game SET description = 'Subnautica is an underwater survival game that combines fear, curiosity, and beauty in one of the genre''s most memorable worlds. Players crash-land on an alien ocean planet and must gradually learn its ecosystems, resources, and hidden dangers in order to survive and escape. The sense of discovery is extraordinary, especially because deeper regions become more mysterious and intimidating instead of simply harder. Crafting and base-building support exploration rather than replace it, giving players practical reasons to push further into the unknown. Audio design and environmental scale make the ocean feel both peaceful and terrifying depending on where you are. The story unfolds quietly through ruins, logs, and gradual realization rather than constant exposition. It is one of the best examples of survival design driven by wonder.' WHERE title = 'Subnautica';

UPDATE game SET description = 'Outer Wilds is a time-loop exploration game built around curiosity, knowledge, and the joy of slowly understanding a solar system. Players pilot a small ship between planets that are all changing in real time, each one shaped by unique rules and mysteries. There is no traditional leveling or combat progression because the true advancement comes from what the player learns. That design makes every discovery feel deeply personal and meaningful. The writing is gentle and philosophical, touching on mortality, legacy, and cosmic scale without becoming heavy-handed. Its soundtrack and atmosphere give the entire journey a reflective tone that lingers long after completion. It is a rare game where knowledge itself becomes the most powerful mechanic.' WHERE title = 'Outer Wilds';

UPDATE game SET description = 'Slay the Spire is a deckbuilding roguelike that turns card synergy, resource management, and route planning into an endlessly replayable strategy loop. Each run asks players to build around relics, card upgrades, and encounters that may or may not support a larger plan. The brilliance of the design lies in how simple the rules feel compared to the depth they produce over time. Every new card reward becomes a small strategic test of discipline and long-term thinking. Different characters encourage completely different styles, which helps keep repeated runs fresh. Randomness exists, but strong decision-making still feels highly rewarded. It is one of the most influential and refined strategy indies of the past decade.' WHERE title = 'Slay the Spire';

UPDATE game SET description = 'Cuphead is a run-and-gun action game famous for its hand-drawn 1930s cartoon art, jazz-influenced soundtrack, and punishing boss encounters. The visual style is instantly recognizable, but the gameplay is equally important because it demands precision, pattern recognition, and calm under pressure. Boss phases are inventive and often wildly theatrical, turning every fight into a performance as much as a challenge. Movement and shooting are simple on paper, yet the game extracts enormous depth from exact timing and positioning. The difficulty can be intense, but the short retry loop keeps players focused and learning. Cooperative play adds a second layer of excitement and chaos. It is a beautiful and demanding action game with a very strong identity.' WHERE title = 'Cuphead';

UPDATE game SET description = 'Forza Motorsport is a racing simulation focused on performance driving, track mastery, and the feel of competitive precision. The game emphasizes braking points, cornering discipline, and gradual improvement rather than the festival-style freedom of Horizon. Cars feel distinct enough to reward tuning and experimentation, especially for players who enjoy dialing in setups. Track presentation is clean and polished, supporting the more serious motorsport atmosphere. Progression encourages continued learning rather than casual collection alone. Multiplayer and event structure help give races a stronger sense of stakes and craft. It is built for players who enjoy racing as skill development rather than pure spectacle.' WHERE title = 'Forza Motorsport';

UPDATE game SET description = 'EA SPORTS FC 24 is a modern football simulation built around licensed clubs, recognizable stars, and competitive online play. The game aims to capture the pace and shape of contemporary football through movement, passing, defensive control, and tactical variation. Career-style modes and team-building systems give players different reasons to engage depending on whether they prefer solo progression or live competition. Presentation is highly polished, reinforcing the feeling of a global sport product with big-match energy. Its core appeal lies in recreating familiar clubs and players in a system that rewards timing and understanding of space. Frequent play is encouraged through events, progression, and the social dimension of football culture itself. It is a strong continuation of the big-budget football sim formula.' WHERE title = 'EA SPORTS FC™ 24';

UPDATE game SET description = 'Mortal Kombat 1 is a cinematic fighting game that combines brutal finishing moves, stylish character design, and accessible but satisfying combat systems. The rebooted timeline gives the story mode room to revisit familiar rivalries with a fresh structure. Fighting feels punchy and dramatic, with strong visual clarity and a reliable sense of impact. Assist mechanics expand combo routes and strategy, helping the game feel modern without losing the recognizable Mortal Kombat identity. Presentation is lavish, especially during story scenes and signature finishing sequences. Longtime fans benefit from the roster''s legacy, while newer players can still enjoy the clear spectacle of each match. It is a polished and highly entertaining entry in one of fighting games'' most recognizable franchises.' WHERE title = 'Mortal Kombat 1';

UPDATE game SET description = 'Sifu is a martial arts action game built around close-range precision, relentless pressure, and the gradual mastery of timing. The central aging mechanic turns repeated failure into a thematic and mechanical system, forcing players to think about progress, cost, and momentum. Combat is all about reading attacks, managing space, and staying calm in crowded encounters. Animations and environmental interactions make fights feel grounded and choreographed at the same time. Levels are compact but replayable, encouraging players to revisit them with greater skill and efficiency. Its tone is serious and disciplined, which helps the action feel focused rather than flashy for its own sake. It is one of the most satisfying recent games about learning through repetition.' WHERE title = 'Sifu';

UPDATE game SET description = 'Returnal is a third-person sci-fi action game that combines roguelike structure with fast movement, bullet-hell intensity, and psychological unease. Players control Selene, trapped in a cycle of death on a hostile alien planet where memory and reality keep slipping into one another. Combat is aggressive and mobile, rewarding players who stay in motion instead of hiding from danger. The game''s visual and audio design create a tense atmosphere that supports both action and mystery. The roguelike loop can be demanding, but it also reinforces the story''s themes of repetition and instability. Environmental storytelling and shifting fragments of narrative keep the experience unsettling and compelling. It is a bold, stylish action game with strong identity and pressure.' WHERE title = 'Returnal™';

UPDATE game SET description = 'Ratchet & Clank: Rift Apart is a colorful action adventure that uses dimensional travel, inventive weapons, and animation-quality presentation to deliver constant energy. The game''s arsenal is one of its biggest strengths, with weapons that are imaginative, humorous, and mechanically expressive. Platforming, combat, and world-hopping are woven together so smoothly that the pacing rarely slows down. The visual fidelity is especially striking, making characters, effects, and environments feel bright and alive. Beneath the spectacle, the story also gives room for character reflection and emotional sincerity. It is approachable for newcomers while still clearly rooted in the charm of a long-running series. The result is a highly polished adventure built for fun, momentum, and visual delight.' WHERE title = 'Ratchet & Clank: Rift Apart';

UPDATE game SET description = 'Age of Empires IV: Anniversary Edition is a real-time strategy game that returns the series to large-scale historical conflict with modern production and strong readability. Players gather resources, build armies, and expand civilizations while managing economic growth and battlefield positioning. Each civilization has enough asymmetry to change strategy meaningfully without making the game inaccessible. The documentary-style presentation adds educational texture and helps reinforce the historical framing. Matches can shift from slow economic setup to massive sieges and tactical pressure in ways that feel satisfying and dramatic. Strong multiplayer support and broad single-player content help the game serve different kinds of strategy fans. It is a successful revival that respects the past while feeling contemporary.' WHERE title = 'Age of Empires IV: Anniversary Edition';

UPDATE game SET description = 'Crusader Kings III is a grand strategy role-playing game about dynasties, politics, inheritance, and the chaos of human ambition. Rather than focusing only on military conquest, it asks players to manage families, marriages, religions, schemes, and succession across generations. Characters are central to the experience, and their traits, rivalries, and ambitions often matter more than maps or numbers alone. The game creates memorable emergent stories because systems constantly collide in unexpected ways. Success can come through diplomacy, manipulation, war, or simply surviving disaster long enough to recover. Despite its complexity, the interface and presentation are much more welcoming than many strategy games in its class. It is a brilliant sandbox for players who enjoy storytelling through systems.' WHERE title = 'Crusader Kings III';

UPDATE game SET description = 'Cities: Skylines II is a city-building simulation focused on planning, infrastructure, services, and the slow complexity of urban growth. The game asks players to think about roads, zoning, traffic, education, economy, and environmental systems as one connected whole. Watching a small town expand into a functioning city can be deeply satisfying because every major success usually comes from many smaller design decisions. Its appeal lies less in dramatic events and more in long-form management and optimization. The scale of the simulation supports a strong sense of authorship over the final city. When everything works, the experience feels both creative and analytical. It is designed for players who enjoy watching systems evolve over time under their guidance.' WHERE title = 'Cities: Skylines II';

UPDATE game SET description = 'Project Zomboid is a hardcore zombie survival sandbox built around vulnerability, simulation depth, and the constant possibility of permanent failure. The game does not present survival as a power fantasy, but as a slow and exhausting attempt to endure against overwhelming odds. Every task matters, from barricading windows and cooking food to managing wounds, fatigue, and panic. The isometric view hides surprising depth, with systems that support stealth, crafting, scavenging, farming, and long-term planning. Multiplayer and modding expand the possibilities even further, turning the world into a stage for many different kinds of survival stories. Its tone is bleak, but that bleakness is exactly what makes success feel meaningful. It is one of the most uncompromising and rewarding zombie sandboxes ever made.' WHERE title = 'Project Zomboid';

UPDATE game SET description = 'Alan Wake 2 is a psychological survival horror game that blends detective structure, meta-fiction, and atmospheric terror into a highly stylized narrative experience. The game alternates perspectives and realities in ways that constantly challenge the player''s understanding of what is happening. Combat is sparse enough to remain tense, while investigation and environmental observation play a much larger role in the overall rhythm. The visual design is moody and dense, filled with darkness, reflections, and uncanny imagery that support the game''s themes. Its writing is ambitious, often leaning into layered storytelling rather than simple clarity. This makes the experience stranger, but also more memorable and distinctive. It is a bold horror sequel built around mood, structure, and artistic confidence.' WHERE title = 'Alan Wake 2';

UPDATE game SET description = 'Dead Cells is a roguelite action platformer that thrives on speed, repetition, and the joy of mastering movement and combat together. Every run sends players through branching paths, random gear choices, and escalating threats that test reflexes and decision-making. Combat feels sharp because dodging, attacking, and repositioning all flow naturally into one another. The game rarely wastes time, which helps failure feel motivating instead of frustrating. Unlocks and permanent progression create long-term goals without undermining the challenge of each run. Its visual style is clean and readable, making the intensity easier to process even when things get frantic. It is one of the strongest examples of how elegant action design can support endless replayability.' WHERE title = 'Dead Cells';

UPDATE game SET description = 'Hi-Fi RUSH is a rhythm-based action game that turns combat, movement, and presentation into one unified performance. Even players who are not naturally focused on rhythm can still enjoy the game, but learning to sync attacks to the beat makes everything feel more powerful and expressive. The world is bright, stylized, and packed with playful visual feedback that reinforces the music-driven identity of the game. Combat mixes basic action mechanics with timing bonuses in a way that feels inviting rather than punishing. Character writing and tone keep the story light, energetic, and easy to enjoy. Set pieces and boss fights also lean heavily into timing and spectacle, making the whole experience feel unusually cohesive. It is one of the most joyful and surprising action games in recent years.' WHERE title = 'Hi-Fi RUSH';

UPDATE game SET description = 'Jusant is a climbing adventure focused on movement, pacing, and the emotional pull of ascending a mysterious vertical world. Instead of conventional combat or large-scale action, the game builds tension through route choice, stamina management, and the physical sensation of climbing. The silence and scale of the environments give the journey a meditative tone. Environmental storytelling slowly reveals what happened to the world and why the climb matters. Its mechanics are simple enough to remain approachable, but deliberate enough to keep the player engaged. The game succeeds because it trusts atmosphere and motion to carry the experience. It is quiet, elegant, and refreshingly different from more conventional action titles.' WHERE title = 'Jusant';

UPDATE game SET description = 'Lethal Company is a cooperative horror game where players scavenge abandoned industrial sites for profit while trying to avoid terrifying threats. Communication is everything, because survival often depends on warning teammates, managing routes, and knowing when to run. The game creates fear not just through monsters, but through uncertainty, isolation, and the knowledge that mistakes can spiral quickly. At the same time, its systems also generate absurd comedy, especially when a plan falls apart in seconds. This blend of dread and chaos is what makes it so compelling with friends. The low-key presentation actually helps the horror by leaving room for imagination and panic. It is a multiplayer horror experience driven by tension, teamwork, and unforgettable disasters.' WHERE title = 'Lethal Company';

UPDATE game SET description = 'Terraria is a 2D sandbox adventure built around mining, crafting, fighting, building, and discovering just how much content can exist beneath a deceptively simple surface. The game begins with basic tools and survival, but gradually expands into boss progression, biome exploration, NPC systems, and powerful gear paths. Combat, mobility, and construction all deepen over time, making the sense of growth especially satisfying. Exploration is one of its great strengths, because every new underground layer or distant biome can reveal resources, structures, or threats that reshape goals. Cooperative play enhances the experience further, turning construction and boss fights into shared projects. Its art style is modest, but the density of systems and surprises gives it huge staying power. It remains one of the best sandbox games ever made.' WHERE title = 'Terraria';

UPDATE game SET description = 'Vampire Survivors is a survival action game built around automatic attacks, movement-based decision-making, and the hypnotic satisfaction of exponential power growth. The premise is simple, but the way upgrades, weapons, and evolutions combine creates a highly addictive feedback loop. Early survival is often tense, but later minutes can become gloriously chaotic as the screen fills with enemies and effects. Unlock systems, hidden interactions, and strange secrets add far more depth than the game initially suggests. Its visual style is deliberately plain, which only makes the elegance of the design more impressive. Sessions are compact, readable, and extremely replayable. It is a small game with enormous mechanical satisfaction.' WHERE title = 'Vampire Survivors';

UPDATE game SET description = 'XCOM 2 is a turn-based tactical strategy game where players lead a resistance movement against alien occupation in a desperate fight for humanity''s future. Missions are tense because every action matters, and the loss of a trained soldier can be emotionally and strategically devastating. The game balances battlefield tactics with wider campaign management, forcing players to split attention between immediate survival and long-term planning. Cover, flanking, abilities, and randomness create dramatic encounters where a perfect plan can still collapse under pressure. Custom soldiers and the memory of past missions help the campaign feel personal. The difficulty can be punishing, but that tension is also what gives victories so much weight. It is one of the strongest modern strategy games for players who enjoy risk, pressure, and consequence.' WHERE title = 'XCOM 2';

UPDATE game SET description = 'Persona 3 Reload is a modern remake of a beloved RPG that combines dungeon crawling, social simulation, and themes of mortality in a stylish package. The game follows a group of students who confront supernatural threats while also navigating school life, friendships, and identity. Its structure creates a compelling contrast between the ordinary routines of daily life and the eerie battles that take place after midnight. Turn-based combat is polished and readable, with elemental weaknesses and party roles giving battles clear strategic shape. The emotional tone is more reflective and somber than in some later Persona entries, which gives the story a distinct weight. Music, interface design, and visual updates help the remake feel fresh without losing the spirit of the original. It is a thoughtful and striking RPG about time, connection, and acceptance.' WHERE title = 'Persona 3 Reload';

UPDATE game SET description = 'Like a Dragon: Infinite Wealth is a large-scale RPG that combines melodrama, humor, turn-based combat, and character warmth in a way few other series attempt. The game continues to build on the strength of its cast, giving major emotional beats room to land while still embracing bizarre side stories and absurd detours. Combat is more playful and spatially expressive than before, making every encounter feel more dynamic. The setting adds variety and helps the adventure feel bigger and more colorful than a typical crime drama. Side activities, minigames, and optional content are extensive, giving the world a sense of excess that fits the series well. Beneath the chaos is a sincere focus on loyalty, aging, regret, and friendship. It is a big-hearted RPG that knows how to balance ridiculous fun with genuine emotion.' WHERE title = 'Like a Dragon: Infinite Wealth';

UPDATE game SET description = 'The Talos Principle 2 is a first-person puzzle game that builds intricate environmental challenges around themes of consciousness, civilization, and philosophical responsibility. Puzzles are carefully layered, often requiring players to understand how multiple systems interact rather than simply spotting one trick. The world is visually beautiful and much larger in scale than many puzzle games, giving the journey a contemplative grandeur. Narrative conversations and written material invite reflection without forcing one rigid interpretation. What makes the game stand out is how successfully it combines mechanical rigor with intellectual curiosity. Progression remains satisfying because every new puzzle still feels grounded in clear rules, even when the ideas become more complex. It is a rare sequel that expands both the brain and the soul of its original.' WHERE title = 'The Talos Principle 2';

UPDATE game SET description = 'RimWorld is a colony simulation and story generator where players manage survivors trying to build a life on a remote world. The game is famous for turning simple systems like mood, health, weather, raids, and relationships into unpredictable narratives full of triumph and disaster. Every colony develops its own identity because characters have distinct traits, weaknesses, and personal histories. Building and resource management are important, but the emotional drama of survival is what makes the game memorable. Crises often emerge from small problems that spiral outward, forcing adaptation instead of routine. The simulation is deep enough to support endless playstyles, from benevolent settlement building to brutal authoritarian control. It is one of the richest sandbox strategy games ever created.' WHERE title = 'RimWorld';

UPDATE game SET description = 'F1 24 is a modern Formula racing game designed around licensed teams, circuit precision, and the tension of high-speed motorsport. Success depends on braking control, corner exits, tire management, and race awareness rather than simple top speed. Career systems and team progression help create a longer arc beyond individual races, giving players reasons to improve and invest over time. Presentation is polished and broadcast-inspired, helping each event feel like part of a larger professional season. Track familiarity and consistent practice are strongly rewarded, which suits the demands of Formula racing. The game works best for players who enjoy measured improvement and technical driving. It is a strong motorsport package built around discipline and speed.' WHERE title = 'F1® 24';

UPDATE game SET description = 'Need for Speed Unbound is a street racing game that mixes arcade driving, city exploration, and a bold visual style built around graffiti-like effects and expressive presentation. The game focuses on illegal racing culture, police pressure, and the constant push to earn more while risking everything. Cars are highly customizable, which helps players feel ownership over both performance and identity. Racing itself is fast and accessible, designed more around style, aggression, and atmosphere than strict realism. The city backdrop supports a sense of rebellious energy, especially during high-risk runs where pursuit and reward escalate together. Its visual direction helps distinguish it from more traditional racers, even when the structure remains familiar. It is a confident arcade racer with attitude and momentum.' WHERE title = 'Need for Speed™ Unbound';

UPDATE game SET description = 'Hunt: Showdown 1896 is a multiplayer extraction shooter that combines gothic horror, tense gunfights, and deliberate pacing in a uniquely oppressive setting. Players enter dangerous maps to track monstrous targets while knowing that rival hunters are doing the same thing. This creates constant tension, because every sound and movement could mean opportunity or sudden death. Weapons feel heavy and old, which slows combat in a way that makes positioning and nerves especially important. The horror atmosphere is not just cosmetic, but central to how the game creates pressure and uncertainty. Matches often produce memorable stories because outcomes can change from one gunshot or one bad decision. It is one of the most distinctive multiplayer shooters for players who enjoy suspense and high stakes.' WHERE title = 'Hunt: Showdown 1896';

COMMIT;