version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_ign
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro
      - ./gamezone_schema.sql:/docker-entrypoint-initdb.d/sql/gamezone_schema.sql:ro
      - ./gamezone_seed.sql:/docker-entrypoint-initdb.d/sql/gamezone_seed.sql:ro
      - ./extra_games.sql:/docker-entrypoint-initdb.d/sql/extra_games.sql:ro
      - ./Description_updated.sql:/docker-entrypoint-initdb.d/sql/Description_updated.sql:ro
      - ./order.sql:/docker-entrypoint-initdb.d/sql/order.sql:ro
    ports:
      - "5432:5432"

volumes:
  db_data:
